---
- name: copy mariadb files
  copy:
    src: mariadb
    dest: /home/{{ ansible_user_id }}/app/requirements

- name: create mariadb data directory
  file:
    path: /home/{{ ansible_user_id }}/data/db_data
    state: directory
    mode: '0755'

- name: generate mariadb config
  template:
    src: mariadb.cnf.j2
    dest: /home/{{ ansible_user_id }}/app/requirements/mariadb/mariadb.cnf
