---
- name: Create wordpress volume Directory
  file:
    path: "/home/{{ ansible_user_id }}/data/wp_data"
    state: directory
    mode: '0755'

- name: Check if WordPress is already installed
  stat:
    path: "/home/{{ ansible_user_id }}/data/wp_data/wp-config.php"
  register: wp_installed

- name: Check if phpmyadmin is already installed
  stat:
    path: "/home/{{ ansible_user_id }}/data/wp_data/phpmyadmin/config.inc.php"
  register: phpmyadmin_installed

- name: Download and install wodpress
  block:
    - name: Download wordpress files
      get_url:
        url: https://wordpress.org/wordpress-6.6.zip
        dest: /home/{{ ansible_user_id }}/data/wp_data/latest.zip

    - name: extract wordpress files
      unarchive:
        src: /home/{{ ansible_user_id }}/data/wp_data/latest.zip
        dest: /home/{{ ansible_user_id }}/data/wp_data
        remote_src: true

    - name: cleanup
      shell: |
        mv /home/{{ ansible_user_id }}/data/wp_data/wordpress/* /home/{{ ansible_user_id }}/data/wp_data
        rm -rf /home/{{ ansible_user_id }}/data/wp_data/wordpress
        rm -rf /home/{{ ansible_user_id }}/data/wp_data/latest.zip

  when: not wp_installed.stat.exists

- name: create wp-config.php
  template:
    src: wp-config.php.j2
    dest: /home/{{ ansible_user_id }}/data/wp_data/wp-config.php

- name: download and install phpmyadmin
  block:
    - name: Download phpmyadmin files
      get_url:
        url: https://files.phpmyadmin.net/phpMyAdmin/5.2.1/phpMyAdmin-5.2.1-all-languages.zip
        dest: /home/{{ ansible_user_id }}/data/wp_data/phpmyadmin.zip

    - name: extract phpmyadmin files
      unarchive:
        src: /home/{{ ansible_user_id }}/data/wp_data/phpmyadmin.zip
        dest: /home/{{ ansible_user_id }}/data/wp_data
        remote_src: true

    - name: cleanup
      shell: |
        mv /home/{{ ansible_user_id }}/data/wp_data/phpMyAdmin-5.1.1-all-languages /home/{{ ansible_user_id }}/data/wp_data/phpmyadmin
        rm -rf /home/{{ ansible_user_id }}/data/wp_data/phpmyadmin.zip
  when: not phpmyadmin_installed.stat.exists

- name: create phpmyadmin config file
  template:
    src: config.inc.php.j2
    dest: /home/{{ ansible_user_id }}/data/wp_data/phpmyadmin/config.inc.php

- name: copy wordpress folder to app directory
  copy:
    src: wordpress
    dest: /home/{{ ansible_user_id }}/app/requirements
